version: "3.9"

services:
  # info from https://hub.docker.com/_/zookeeper
  zookeeper1:
    image: zookeeper:3.6
    hostname: zookeeper1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=zookeeper3:2888:3888;2181

  zookeeper2:
    image: zookeeper:3.6
    hostname: zookeeper2
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zookeeper1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zookeeper3:2888:3888;2181

  zookeeper3:
    image: zookeeper:3.6
    hostname: zookeeper3
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zookeeper1:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181

  # info from https://hub.docker.com/r/bitnami/kafka
  kafka1:
    image: bitnami/kafka:2.7.0
    ports:
      - 9092:9092
    environment: 
      # KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper1:2181
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
    depends_on: 
      - zookeeper1
      - zookeeper2
      - zookeeper3

  kafka2:
    image: bitnami/kafka:2.7.0
    ports:
      - 9093:9092
    environment: 
      # KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper1:2181
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
    depends_on: 
      - zookeeper1
      - zookeeper2
      - zookeeper3

  kafka3:
    image: bitnami/kafka:2.7.0
    ports:
      - 9094:9092
    environment: 
      # KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper1:2181
      KAFKA_BROKER_ID: 3
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
    depends_on: 
      - zookeeper1
      - zookeeper2
      - zookeeper3

  message_producer:
    build: 
      context: ./MessageProducer
    depends_on: 
      - kafka1